name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake ..
        make -j
        make -j placedatatests

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./placedatatests
      
